### ISSUE TITLE
Code is vulnerable to many SQL injection attacks

### ISSUE THREAD

**Issue by AeroNotix** [brentmorgan/audioplayer#1]
There are many places where you blindly interpolate the $_POST data into an SQL statement.

You should use prepared statements.

[Here's a link explaining what they are.](http://pl1.php.net/pdo.prepared-statements)

**Comment by brentmorgan** [comment]
Thanks! Yeah this is still very much a work in progress. Thanks for the link.

**Comment by AeroNotix** [comment]
No worries

**Comment by AeroNotix** [comment]
https://github.com/brentmorgan/audioplayer/blob/master/upload.php#L55 code is still vulnerable.

You need to use prepared statements.

**Comment by brentmorgan** [comment]
lol i know, i haven't worked on this thing in a long time. might get back to it eventually. thanks for checking in tho!

**Comment by AeroNotix** [comment]
:+1:
